# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9 on 2016-01-30 08:23
=======
# Generated by Django 1.9.1 on 2016-01-30 07:31
>>>>>>> 85f3526f7f9ed2b98ec2a522110de12489ec190e
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=10, unique=True)),
<<<<<<< HEAD
                ('m_email', models.CharField(max_length=30, unique=True)),
                ('m_pass', models.CharField(max_length=60)),
=======
>>>>>>> 85f3526f7f9ed2b98ec2a522110de12489ec190e
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=20, unique=True)),
                ('m_idx', models.ManyToManyField(to='slang.Member')),
            ],
        ),
    ]
