# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='m_pass',
        ),
    ]
