# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slang', '0002_remove_member_m_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='m_pass',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
